# Generated by Django 4.1 on 2022-09-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_blog_created_at_blog_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=40, unique=True),
        ),
    ]
